fullnameOverride: kube-state-metrics

resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi

podLabels:
  observability.dsqr.dev/component: kube-state-metrics
