# Terminal Development Layout (tdl), multi-project layouts (tdlm), and
# Terminal Swarm Layout (tsl). HERDR_LAYOUT_CONFIG is generated by Nix.

def herdr-layout-error [message: string] {
  error make { msg: $message }
}

def herdr-layout-exec [arguments: list<string>] {
  let completed = (
    do { ^$HERDR_LAYOUT_CONFIG.binary ...$arguments }
    | complete
  )

  if $completed.exit_code != 0 {
    let details = ($completed.stderr | str trim)
    herdr-layout-error (
      if ($details | is-empty) {
        $"Herdr command failed: ($arguments | str join ' ')"
      } else {
        $details
      }
    )
  }

  $completed.stdout | str trim
}

def herdr-layout-json [arguments: list<string>] {
  let output = (herdr-layout-exec $arguments)
  if ($output | is-empty) {
    herdr-layout-error $"Herdr returned no JSON for: ($arguments | str join ' ')"
  }
  $output | from json
}

def herdr-layout-agent [name: string] {
  let agent = ($HERDR_LAYOUT_CONFIG.agents | get -o $name)
  if $agent == null {
    let available = ($HERDR_LAYOUT_CONFIG.agents | columns | str join ", ")
    herdr-layout-error $"Unknown agent '($name)'. Available agents: ($available)"
  }
  $agent
}

def herdr-layout-project-root [directory: path] {
  let candidate = ($directory | path expand)
  let resolved = (
    do { ^git -C $candidate rev-parse --show-toplevel }
    | complete
  )

  if $resolved.exit_code == 0 {
    $resolved.stdout | str trim | path expand
  } else {
    $candidate
  }
}

def herdr-layout-is-repository-root [directory: path] {
  let candidate = ($directory | path expand)
  let resolved = (
    do { ^git -C $candidate rev-parse --show-toplevel }
    | complete
  )

  $resolved.exit_code == 0 and (($resolved.stdout | str trim | path expand) == $candidate)
}

def herdr-layout-existing-workspace [layout: string, directory: path] {
  let workspaces = (
    herdr-layout-json ["workspace" "list"]
    | get result.workspaces
  )

  $workspaces
  | where { |workspace|
      let tokens = ($workspace | get -o tokens | default {})
      (($tokens | get -o dsqr_layout | default "") == $layout)
        and (($tokens | get -o dsqr_cwd | default "") == ($directory | path expand))
    }
  | get 0?
}

def herdr-layout-record-workspace [
  workspace_id: string
  layout: string
  directory: path
  --agent: string
] {
  mut arguments = [
    "workspace"
    "report-metadata"
    $workspace_id
    "--source"
    "dsqr:layouts"
    "--token"
    $"dsqr_layout=($layout)"
    "--token"
    $"dsqr_cwd=($directory | path expand)"
  ]

  if $agent != null {
    $arguments = ($arguments | append ["--token" $"dsqr_agent=($agent)"])
  }

  herdr-layout-exec $arguments | ignore
}

# Build or focus an editor + agent + shell workspace for one project.
def tdl [
  agent: string = "codex"
  --cwd: path
  --focus: string = "agent"
  --new
] {
  let agent_definition = (herdr-layout-agent $agent)
  let requested_directory = ($cwd | default $env.PWD)
  let project_root = (herdr-layout-project-root $requested_directory)

  if $focus not-in ["agent" "editor" "none"] {
    herdr-layout-error "--focus must be one of: agent, editor, none"
  }

  if not $new {
    let existing = (herdr-layout-existing-workspace "tdl" $project_root)
    if $existing != null {
      if $focus != "none" {
        herdr-layout-exec ["workspace" "focus" $existing.workspace_id] | ignore
      }
      return {
        created: false
        layout: "tdl"
        project: ($project_root | path basename)
        path: $project_root
        workspace_id: $existing.workspace_id
        agent: $agent
      }
    }
  }

  let created = (
    herdr-layout-json [
      "workspace"
      "create"
      "--cwd"
      $project_root
      "--label"
      ($project_root | path basename)
      "--no-focus"
    ]
  )
  let workspace_id = $created.result.workspace.workspace_id
  let editor_pane = $created.result.root_pane.pane_id

  herdr-layout-record-workspace $workspace_id "tdl" $project_root --agent $agent

  let agent_split = (
    herdr-layout-json [
      "pane"
      "split"
      $editor_pane
      "--direction"
      "right"
      "--ratio"
      "0.60"
      "--no-focus"
    ]
  )
  let agent_pane = $agent_split.result.pane.pane_id

  let shell_split = (
    herdr-layout-json [
      "pane"
      "split"
      $agent_pane
      "--direction"
      "down"
      "--ratio"
      "0.68"
      "--no-focus"
    ]
  )
  let shell_pane = $shell_split.result.pane.pane_id

  herdr-layout-exec [
    "pane"
    "run"
    $editor_pane
    $HERDR_LAYOUT_CONFIG.editorCommand
  ] | ignore

  let agent_name = $"tdl-($agent)-($workspace_id)"
  let start_arguments = (
    [
      "agent"
      "start"
      $agent_name
      "--kind"
      $agent_definition.kind
      "--pane"
      $agent_pane
      "--timeout"
      "60000"
      "--"
    ]
    | append $agent_definition.args
  )
  herdr-layout-json $start_arguments | ignore

  if $focus == "agent" {
    herdr-layout-exec ["agent" "focus" $agent_name] | ignore
  } else if $focus == "editor" {
    herdr-layout-exec ["workspace" "focus" $workspace_id] | ignore
  }

  {
    created: true
    layout: "tdl"
    project: ($project_root | path basename)
    path: $project_root
    workspace_id: $workspace_id
    editor_pane: $editor_pane
    agent_pane: $agent_pane
    shell_pane: $shell_pane
    agent: $agent_name
  }
}

# Build tdl workspaces for immediate child Git repositories.
def tdlm [
  agent: string = "codex"
  --root: path
  --limit: int
  --dry-run
] {
  herdr-layout-agent $agent | ignore

  let scan_root = ($root | default $env.PWD | path expand)
  let effective_limit = ($limit | default $HERDR_LAYOUT_CONFIG.maxProjects)
  if $effective_limit < 1 {
    herdr-layout-error "--limit must be positive"
  }

  let repositories = (
    ls $scan_root
    | where type == dir
    | get name
    | each { |directory| $directory | path expand }
    | where { |directory|
        let visible = not (($directory | path basename) | str starts-with ".")
        $visible and (herdr-layout-is-repository-root $directory)
      }
    | sort
  )

  if ($repositories | is-empty) {
    herdr-layout-error $"No immediate Git repositories found under ($scan_root)"
  }

  if ($repositories | length) > $effective_limit {
    herdr-layout-error (
      $"Found ($repositories | length) repositories; --limit is ($effective_limit). "
      + "Increase the limit explicitly after reviewing --dry-run."
    )
  }

  let preview = (
    $repositories
    | each { |repository|
        {
          project: ($repository | path basename)
          path: $repository
          agent: $agent
        }
      }
  )

  if $dry_run {
    return $preview
  }

  mut layouts = []
  for repository in $repositories {
    let layout = (tdl $agent --cwd $repository --focus "none")
    $layouts = ($layouts | append $layout)
  }

  let first_workspace = ($layouts | get 0?.workspace_id)
  if $first_workspace != null {
    herdr-layout-exec ["workspace" "focus" $first_workspace] | ignore
  }

  $layouts
}

# Build a balanced grid of agents sharing the current checkout.
def tsl [
  panes: int
  agent: string = "codex"
  --cwd: path
  --shared
] {
  let agent_definition = (herdr-layout-agent $agent)
  if not $shared {
    herdr-layout-error (
      "tsl starts multiple agents in one checkout. Pass --shared only for "
      + "read-only/research work; worktree-backed swarms come later."
    )
  }

  if $panes < 2 or $panes > $HERDR_LAYOUT_CONFIG.maxSwarmPanes {
    herdr-layout-error (
      $"panes must be between 2 and ($HERDR_LAYOUT_CONFIG.maxSwarmPanes)"
    )
  }

  let requested_directory = ($cwd | default $env.PWD)
  let project_root = (herdr-layout-project-root $requested_directory)
  let project_name = ($project_root | path basename)
  let created = (
    herdr-layout-json [
      "workspace"
      "create"
      "--cwd"
      $project_root
      "--label"
      $"($project_name)-swarm"
      "--no-focus"
    ]
  )
  let workspace_id = $created.result.workspace.workspace_id
  let root_pane = $created.result.root_pane.pane_id

  herdr-layout-record-workspace $workspace_id "tsl" $project_root --agent $agent

  let columns = ($panes | math sqrt | math ceil | into int)
  mut column_panes = [$root_pane]
  mut remaining_pane = $root_pane

  if $columns > 1 {
    for split_index in 1..<$columns {
      let remaining_columns = ($columns - $split_index + 1)
      let ratio = (1.0 / $remaining_columns | into string)
      let split = (
        herdr-layout-json [
          "pane"
          "split"
          $remaining_pane
          "--direction"
          "right"
          "--ratio"
          $ratio
          "--no-focus"
        ]
      )
      $remaining_pane = $split.result.pane.pane_id
      $column_panes = ($column_panes | append $remaining_pane)
    }
  }

  let base_rows = (($panes / $columns) | math floor | into int)
  let extra_rows = ($panes mod $columns)
  mut agent_panes = []

  for column in ($column_panes | enumerate) {
    let row_count = (
      $base_rows
      + if $column.index < $extra_rows { 1 } else { 0 }
    )
    $agent_panes = ($agent_panes | append $column.item)

    if $row_count == 2 {
      let split = (
        herdr-layout-json [
          "pane"
          "split"
          $column.item
          "--direction"
          "down"
          "--ratio"
          "0.50"
          "--no-focus"
        ]
      )
      $agent_panes = ($agent_panes | append $split.result.pane.pane_id)
    }
  }

  mut agents = []
  for pane in ($agent_panes | enumerate) {
    let agent_name = $"tsl-($agent)-($workspace_id)-($pane.index + 1)"
    let start_arguments = (
      [
        "agent"
        "start"
        $agent_name
        "--kind"
        $agent_definition.kind
        "--pane"
        $pane.item
        "--timeout"
        "60000"
        "--"
      ]
      | append $agent_definition.args
    )
    herdr-layout-json $start_arguments | ignore
    $agents = ($agents | append $agent_name)
  }

  herdr-layout-exec ["workspace" "focus" $workspace_id] | ignore
  herdr-layout-exec ["agent" "focus" ($agents | first)] | ignore

  {
    created: true
    layout: "tsl"
    project: $project_name
    path: $project_root
    workspace_id: $workspace_id
    agents: $agents
    shared_checkout: true
  }
}
